version: '3.8'
services:
  localdb:
    container_name: localdb
    image: postgres:13.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    privileged: true

volumes:
  postgres_data:
  node_modules:
